import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper';

export const AppTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#F39C12',
    onPrimary: '#FFFFFF',
    primaryContainer: '#F39C12',
    onPrimaryContainer: '#FFFFFF',
    secondary: '#3498DB',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#3498DB',
    onSecondaryContainer: '#FFFFFF',
    background: '#FFFFFF',
    onBackground: '#000000',
    surface: '#FFFFFF',
    onSurface: '#000000',
    surfaceVariant: '#F5F5F5',
    onSurfaceVariant: '#666666',
    error: '#F44336',
    onError: '#FFFFFF',
    outline: '#DDDDDD',
    outlineVariant: '#CCCCCC',
    scrim: '#000000',
    shadow: '#000000',
    inverseSurface: '#222222',
    inverseOnSurface: '#FFFFFF',
    inversePrimary: '#F39C12',
    elevation: {
      level0: 'transparent',
      level1: '#F5F5F5',
      level2: '#EEEEEE',
      level3: '#E0E0E0',
      level4: '#D5D5D5',
      level5: '#CCCCCC',
    },
  },
  roundness: 8,
  fonts: {
    ...MD3LightTheme.fonts,
    headlineLarge: {
      ...MD3LightTheme.fonts.headlineLarge,
      fontSize: 32,
      fontWeight: 'bold',
    },
    headlineMedium: {
      ...MD3LightTheme.fonts.headlineMedium,
      fontSize: 24,
      fontWeight: 'bold',
    },
    bodyLarge: {
      ...MD3LightTheme.fonts.bodyLarge,
      fontSize: 16,
    },
    bodyMedium: {
      ...MD3LightTheme.fonts.bodyMedium,
      fontSize: 14,
    },
  },
};

export const DarkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#F39C12',
    onPrimary: '#000000',
    primaryContainer: '#F39C12',
    onPrimaryContainer: '#FFFFFF',
    secondary: '#3498DB',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#3498DB',
    onSecondaryContainer: '#FFFFFF',
    background: '#121212',
    onBackground: '#FFFFFF',
    surface: '#1E1E1E',
    onSurface: '#FFFFFF',
    surfaceVariant: '#2C2C2C',
    onSurfaceVariant: '#B0B0B0',
    error: '#F44336',
    onError: '#FFFFFF',
    outline: '#404040',
    outlineVariant: '#333333',
    scrim: '#000000',
    shadow: '#000000',
    inverseSurface: '#F5F5F5',
    inverseOnSurface: '#000000',
    inversePrimary: '#F39C12',
    elevation: {
      level0: 'transparent',
      level1: '#2C2C2C',
      level2: '#333333',
      level3: '#404040',
      level4: '#4D4D4D',
      level5: '#5A5A5A',
    },
  },
  roundness: 8,
  fonts: AppTheme.fonts,
};
